name: jsbackend CI
​
on:
  pull_request:
    branches: [toni]
​
jobs:
  build:
    runs-on: ubuntu-latest
​
    steps:
      - name: Checkout Out Repo
        uses: actions/checkout@v2
​
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
​
      - name: Build
        id: docker_builder
        uses: docker/build-push-action@v2
        with:
          context: ./jsbackend
          file: ./jsbackend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jsbackend:latest
​
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}